name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: unreal/ups
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.unreal.codes
          tags: "latest,${{ env.GITHUB_RUN_NUMBER }}"